<Project Sdk="Transpose.Build.Target/26.7.3049">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Transpose.BCL" Version="26.7.3120" />
    <PackageReference Include="Transpose.Core" Version="26.7.3122" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tesserae\Tesserae.csproj" />
  </ItemGroup>
</Project>
