// <auto-generated />
// Palettes for the PixelAvatar component, extracted from the source cat sprite sheets.
// Each entry maps palette index 1..N to a CSS color; index 0 is transparent and is not
// stored. Do not edit by hand.

using System.Collections.Generic;

namespace Tesserae
{
    /// <summary>
    /// The built-in <see cref="PixelAvatarPalette"/> for each <see cref="PixelAvatarDesign"/>.
    /// </summary>
    [Transpose.Name("tss.PixelAvatarPalettes")]
    public static class PixelAvatarPalettes
    {
        private static readonly Dictionary<PixelAvatarDesign, PixelAvatarPalette> _palettes = Build();

        /// <summary>
        /// Returns the palette for one of the built-in designs.
        /// </summary>
        public static PixelAvatarPalette Get(PixelAvatarDesign design) => _palettes[design];

        /// <summary>
        /// Returns every built-in design, in declaration order.
        /// </summary>
        public static PixelAvatarDesign[] All => new[]
        {
            PixelAvatarDesign.Black,
            PixelAvatarDesign.Orange,
            PixelAvatarDesign.White,
            PixelAvatarDesign.Beige,
            PixelAvatarDesign.Siamese,
            PixelAvatarDesign.SpottedGrey,
            PixelAvatarDesign.SpottedOrange,
            PixelAvatarDesign.Tuxedo,
        };

        private static Dictionary<PixelAvatarDesign, PixelAvatarPalette> Build()
        {
            var palettes = new Dictionary<PixelAvatarDesign, PixelAvatarPalette>();

            palettes[PixelAvatarDesign.Black] = new PixelAvatarPalette("Black", new[] { "#625565", "#625565", "#625565", "#3E3546", "#3E3546", "#3E3546", "#3E3546", "#3E3546", "#3E3546", "#2E222F", "#2E222F" });
            palettes[PixelAvatarDesign.Orange] = new PixelAvatarPalette("Orange", new[] { "#F79617", "#F79617", "#F79617", "#FB6B1D", "#FB6B1D", "#FB6B1D", "#FB6B1D", "#FB6B1D", "#FB6B1D", "#E83B3B", "#E83B3B" });
            palettes[PixelAvatarDesign.White] = new PixelAvatarPalette("White", new[] { "#FFFFFF", "#FFFFFF", "#FFFFFF", "#C7DCD0", "#C7DCD0", "#C7DCD0", "#C7DCD0", "#C7DCD0", "#C7DCD0", "#9BABB2", "#9BABB2" });
            palettes[PixelAvatarDesign.Beige] = new PixelAvatarPalette("Beige", new[] { "#FDCBB0", "#FDCBB0", "#FDCBB0", "#FCA790", "#FCA790", "#FCA790", "#FCA790", "#FCA790", "#FCA790", "#F68181", "#F68181" });
            palettes[PixelAvatarDesign.Siamese] = new PixelAvatarPalette("Siamese", new[] { "#3E3546", "#FDE3D5", "#3E3546", "#FDCBB0", "#625565", "#FDCBB0", "#3E3546", "#625565", "#FDCBB0", "#3E3546", "#FCA790" });
            palettes[PixelAvatarDesign.SpottedGrey] = new PixelAvatarPalette("SpottedGrey", new[] { "#FFFFFF", "#FFFFFF", "#9BABB2", "#9BABB2", "#C7DCD0", "#C7DCD0", "#C7DCD0", "#9BABB2", "#C7DCD0", "#7E8F96", "#7E8F96" });
            palettes[PixelAvatarDesign.SpottedOrange] = new PixelAvatarPalette("SpottedOrange", new[] { "#FFFFFF", "#FFFFFF", "#F9C22B", "#F79617", "#C7DCD0", "#C7DCD0", "#C7DCD0", "#F79617", "#C7DCD0", "#9BABB2", "#9BABB2" });
            palettes[PixelAvatarDesign.Tuxedo] = new PixelAvatarPalette("Tuxedo", new[] { "#625565", "#625565", "#625565", "#3E3546", "#3E3546", "#3E3546", "#3E3546", "#3E3546", "#C7DCD0", "#2E222F", "#9BABB2" });

            return palettes;
        }
    }
}
