// <auto-generated />
// Designs and palettes for the PixelAvatar component. Each entry maps palette index 1..N
// to a color, plus the background an avatar-shaped host sits the coat on; index 0 is
// transparent and is not stored. The first designs are
// extracted from the source cat sprite sheets; the rest are authored against the same
// index roles. The enum lives here so a new design is a single edit. Do not edit by hand.

using System.Collections.Generic;
using Transpose;

namespace Tesserae
{
    /// <summary>
    /// The available coat designs for a <see cref="PixelAvatar"/>. All designs share the same
    /// artwork and differ only in their <see cref="PixelAvatarPalette"/>.
    /// </summary>
    [Enum(Emit.StringName)]
    [Transpose.Name("tss.PixelAvatarDesign")]
    public enum PixelAvatarDesign
    {
        [Name("Black")]         Black,
        [Name("Orange")]        Orange,
        [Name("White")]         White,
        [Name("Beige")]         Beige,
        [Name("Siamese")]       Siamese,
        [Name("SpottedGrey")]   SpottedGrey,
        [Name("SpottedOrange")] SpottedOrange,
        [Name("Tuxedo")]        Tuxedo,
        [Name("Grey")]          Grey,
        [Name("Sparkle")]       Sparkle,
        [Name("Lynx")]          Lynx
    }

    /// <summary>
    /// The built-in <see cref="PixelAvatarPalette"/> for each <see cref="PixelAvatarDesign"/>.
    /// </summary>
    [Transpose.Name("tss.PixelAvatarPalettes")]
    public static class PixelAvatarPalettes
    {
        private static readonly Dictionary<PixelAvatarDesign, PixelAvatarPalette> _palettes = Build();

        /// <summary>
        /// Returns the palette for one of the built-in designs.
        /// </summary>
        public static PixelAvatarPalette Get(PixelAvatarDesign design) => _palettes[design];

        /// <summary>
        /// Returns every built-in design, in declaration order.
        /// </summary>
        public static PixelAvatarDesign[] All => new[]
        {
            PixelAvatarDesign.Black,
            PixelAvatarDesign.Orange,
            PixelAvatarDesign.White,
            PixelAvatarDesign.Beige,
            PixelAvatarDesign.Siamese,
            PixelAvatarDesign.SpottedGrey,
            PixelAvatarDesign.SpottedOrange,
            PixelAvatarDesign.Tuxedo,
            PixelAvatarDesign.Grey,
            PixelAvatarDesign.Sparkle,
            PixelAvatarDesign.Lynx,
        };

        // Shorthand so the palette rows below stay readable.
        private static Color C(string hex) => Color.FromString(hex);

        private static Dictionary<PixelAvatarDesign, PixelAvatarPalette> Build()
        {
            var palettes = new Dictionary<PixelAvatarDesign, PixelAvatarPalette>();

            palettes[PixelAvatarDesign.Black] = PixelAvatarPalette.FromColors("Black", C("#3340CC"), C("#625565"), C("#625565"), C("#625565"), C("#3E3546"), C("#3E3546"), C("#3E3546"), C("#3E3546"), C("#3E3546"), C("#3E3546"), C("#2E222F"), C("#2E222F"));
            palettes[PixelAvatarDesign.Orange] = PixelAvatarPalette.FromColors("Orange", C("#33B2CC"), C("#F79617"), C("#F79617"), C("#F79617"), C("#FB6B1D"), C("#FB6B1D"), C("#FB6B1D"), C("#FB6B1D"), C("#FB6B1D"), C("#FB6B1D"), C("#E83B3B"), C("#E83B3B"));
            palettes[PixelAvatarDesign.White] = PixelAvatarPalette.FromColors("White", C("#CC338C"), C("#FFFFFF"), C("#FFFFFF"), C("#FFFFFF"), C("#C7DCD0"), C("#C7DCD0"), C("#C7DCD0"), C("#C7DCD0"), C("#C7DCD0"), C("#C7DCD0"), C("#9BABB2"), C("#9BABB2"));
            palettes[PixelAvatarDesign.Beige] = PixelAvatarPalette.FromColors("Beige", C("#33CC8C"), C("#FDCBB0"), C("#FDCBB0"), C("#FDCBB0"), C("#FCA790"), C("#FCA790"), C("#FCA790"), C("#FCA790"), C("#FCA790"), C("#FCA790"), C("#F68181"), C("#F68181"));
            palettes[PixelAvatarDesign.Siamese] = PixelAvatarPalette.FromColors("Siamese", C("#CC6633"), C("#3E3546"), C("#FDE3D5"), C("#3E3546"), C("#FDCBB0"), C("#625565"), C("#FDCBB0"), C("#3E3546"), C("#625565"), C("#FDCBB0"), C("#3E3546"), C("#FCA790"));
            palettes[PixelAvatarDesign.SpottedGrey] = PixelAvatarPalette.FromColors("SpottedGrey", C("#7333CC"), C("#FFFFFF"), C("#FFFFFF"), C("#9BABB2"), C("#9BABB2"), C("#C7DCD0"), C("#C7DCD0"), C("#C7DCD0"), C("#9BABB2"), C("#C7DCD0"), C("#7E8F96"), C("#7E8F96"));
            palettes[PixelAvatarDesign.SpottedOrange] = PixelAvatarPalette.FromColors("SpottedOrange", C("#66CC33"), C("#FFFFFF"), C("#FFFFFF"), C("#F9C22B"), C("#F79617"), C("#C7DCD0"), C("#C7DCD0"), C("#C7DCD0"), C("#F79617"), C("#C7DCD0"), C("#9BABB2"), C("#9BABB2"));
            palettes[PixelAvatarDesign.Tuxedo] = PixelAvatarPalette.FromColors("Tuxedo", C("#CC3359"), C("#625565"), C("#625565"), C("#625565"), C("#3E3546"), C("#3E3546"), C("#3E3546"), C("#3E3546"), C("#3E3546"), C("#C7DCD0"), C("#2E222F"), C("#9BABB2"));

            // Authored rather than extracted:
            // A plain neutral grey, built from three shades like the other single-hue coats.
            palettes[PixelAvatarDesign.Grey] = PixelAvatarPalette.FromColors("Grey", C("#CCA633"), C("#C9CDD4"), C("#C9CDD4"), C("#C9CDD4"), C("#98A0AC"), C("#98A0AC"), C("#98A0AC"), C("#98A0AC"), C("#98A0AC"), C("#98A0AC"), C("#646C7A"), C("#646C7A"));
            // A violet coat with luminous magenta markings and a pale chest.
            palettes[PixelAvatarDesign.Sparkle] = PixelAvatarPalette.FromColors("Sparkle", C("#A6CC33"), C("#E7D6FF"), C("#F7EEFF"), C("#F19BEC"), C("#C63FE3"), C("#9366F5"), C("#9366F5"), C("#9366F5"), C("#C63FE3"), C("#F0E5FF"), C("#4C1D95"), C("#B9A2F2"));
            // A tawny coat with dark brown ear tufts and spots over a cream chest.
            palettes[PixelAvatarDesign.Lynx] = PixelAvatarPalette.FromColors("Lynx", C("#338CCC"), C("#E3CDA8"), C("#F0E2C8"), C("#9A7448"), C("#7A5630"), C("#C4A375"), C("#C4A375"), C("#C4A375"), C("#7A5630"), C("#F5EAD6"), C("#5A3F24"), C("#C7B291"));

            return palettes;
        }
    }
}
