// <auto-generated />
// Sprite data for the PixelAvatar component, generated from the source cat sprite
// sheets. Every sheet shares the same silhouette, so the artwork is stored once as a
// grid of palette indices and each design is only a palette. Do not edit by hand.

using System.Collections.Generic;

namespace Tesserae
{
    /// <summary>
    /// The built-in sprite data shared by every <see cref="PixelAvatar"/>: one frame grid
    /// per animation, where each cell is an index into a <see cref="PixelAvatarPalette"/>
    /// (0 meaning transparent).
    /// </summary>
    [Transpose.Name("tss.PixelAvatarSprites")]
    public static class PixelAvatarSprites
    {
        /// <summary>Width, in pixels, of every sprite frame.</summary>
        public const int FrameWidth = 10;
        /// <summary>Height, in pixels, of every sprite frame.</summary>
        public const int FrameHeight = 8;
        /// <summary>Number of colors in a palette (palette index 0 is always transparent).</summary>
        public const int PaletteSize = 11;
        /// <summary>Highest palette index belonging to the highlight shade.</summary>
        public const int LastHighlightIndex = 3;
        /// <summary>Highest palette index belonging to the base shade; the rest are shadow.</summary>
        public const int LastBaseIndex = 9;

        /// <summary>
        /// How many pixels across the whole sprite sheet use each palette index, indexed by
        /// palette index (entry 0 is the transparent index and is always 0). Lets callers work
        /// out which color covers most of the artwork - see
        /// <see cref="PixelAvatarPalette.DominantColor"/>.
        /// </summary>
        public static readonly int[] PixelCounts = new[] { 0, 128, 89, 43, 133, 133, 66, 43, 43, 2, 73, 38 };

        // Frames are packed as one string per animation: FrameWidth * FrameHeight
        // characters per frame, laid out row by row. '.' is transparent and '1'..'9','a','b'
        // are palette indices 1..11. Strings keep the generated source small and decode to
        // the byte grids below on first use.
        private const string Alphabet = ".123456789ab";

        private static readonly Dictionary<PixelAvatarAnimation, PixelSpriteAnimation> _animations = Build();

        /// <summary>
        /// Returns the frames and timing for the requested animation.
        /// </summary>
        public static PixelSpriteAnimation Get(PixelAvatarAnimation animation) => _animations[animation];

        /// <summary>
        /// Returns which of the three shading levels a palette index belongs to. The indices are
        /// ordered so that each shade is a contiguous run, which is why the single-hue designs
        /// (Black, Orange, White, Beige) are just three colors repeated. Only meaningful for
        /// indices 1..<see cref="PaletteSize"/>.
        /// </summary>
        public static PixelAvatarShade ShadeOf(byte paletteIndex)
        {
            if (paletteIndex <= LastHighlightIndex) return PixelAvatarShade.Highlight;
            if (paletteIndex <= LastBaseIndex) return PixelAvatarShade.Base;
            return PixelAvatarShade.Shadow;
        }

        /// <summary>
        /// Returns every built-in animation, in declaration order.
        /// </summary>
        public static PixelAvatarAnimation[] All => new[]
        {
            PixelAvatarAnimation.Move,
            PixelAvatarAnimation.Idle,
            PixelAvatarAnimation.Interact,
            PixelAvatarAnimation.JumpUp,
            PixelAvatarAnimation.JumpDown,
            PixelAvatarAnimation.Startle,
            PixelAvatarAnimation.Stretch,
            PixelAvatarAnimation.Sit,
            PixelAvatarAnimation.SitIdle,
            PixelAvatarAnimation.Crouch,
            PixelAvatarAnimation.CrouchIdle,
            PixelAvatarAnimation.Sleep,
            PixelAvatarAnimation.SleepIdle,
        };

        private static Dictionary<PixelAvatarAnimation, PixelSpriteAnimation> Build()
        {
            var animations = new Dictionary<PixelAvatarAnimation, PixelSpriteAnimation>();

            Add(animations, PixelAvatarAnimation.Move, 80, true, PixelAvatarAnimation.Move, new[]
            {
                ".........." +
                ".........." +
                ".........." +
                ".....1.3.." +
                ".11..644.." +
                "...22575.." +
                "...44bb..." +
                "...8a5a...",
                ".........." +
                ".........." +
                "......1.3." +
                "......644." +
                ".11..2575." +
                "...226bb.." +
                "...44.5a.." +
                "...8a.....",
                ".........." +
                ".........." +
                ".........." +
                ".11...1.3." +
                "...22.644." +
                "...442575." +
                "..8a.69b.." +
                ".......5a.",
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                "..1..1.3.." +
                "...22644.." +
                "...44575.." +
                "...8a5a...",
            });

            Add(animations, PixelAvatarAnimation.Idle, 260, true, PixelAvatarAnimation.Idle, new[]
            {
                ".........." +
                ".........." +
                ".........." +
                ".....1.3.." +
                ".11..644.." +
                "...22575.." +
                "...44bb..." +
                "...8a5a...",
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                ".11..1.3.." +
                "...22644.." +
                "...44575.." +
                "...8a5a...",
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                ".....1.3.." +
                ".11..644.." +
                "...22575.." +
                "...8a5a...",
            });

            Add(animations, PixelAvatarAnimation.Interact, 140, false, PixelAvatarAnimation.Idle, new[]
            {
                ".........." +
                ".........." +
                ".........." +
                "......1.3." +
                "..11..644." +
                "....22575." +
                "....44bbaa" +
                "...8a.5...",
                ".........." +
                ".........." +
                ".........." +
                "......1.3." +
                "..11..644." +
                "....22575." +
                "....44bb.." +
                "...8a.5.a.",
            });

            Add(animations, PixelAvatarAnimation.JumpUp, 110, false, PixelAvatarAnimation.JumpDown, new[]
            {
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                ".....1.3.." +
                ".1122644.." +
                "...44575.." +
                "...8a5a...",
                ".........." +
                ".........." +
                "......1.3." +
                "......644." +
                ".11..2575." +
                "...226bb.." +
                "...44.5a.." +
                "...8a.....",
            });

            Add(animations, PixelAvatarAnimation.JumpDown, 110, false, PixelAvatarAnimation.Idle, new[]
            {
                ".........." +
                ".........." +
                ".........." +
                ".11...1.3." +
                "...22.644." +
                "...442575." +
                "..8a.69b.." +
                ".......5a.",
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                ".11..1.3.." +
                "...22644.." +
                "...44575.." +
                "...8a5a...",
            });

            Add(animations, PixelAvatarAnimation.Startle, 100, false, PixelAvatarAnimation.Idle, new[]
            {
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                ".....1.3.." +
                ".1122644.." +
                "...44575.." +
                "...8a5a...",
                "...1.1.3.." +
                "...1.644.." +
                "...62575.." +
                "...44bb..." +
                "..8....5.." +
                ".........." +
                ".........." +
                "..........",
                ".........." +
                ".....1.3.." +
                "..1..644.." +
                "..1..575.." +
                "...22bb..." +
                "...4466..." +
                "...8..5..." +
                "..........",
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                ".....1.3.." +
                ".11..644.." +
                "...22575.." +
                "...8a5a...",
            });

            Add(animations, PixelAvatarAnimation.Stretch, 120, false, PixelAvatarAnimation.Sit, new[]
            {
                ".........." +
                ".........." +
                ".........." +
                "....1.3..." +
                "11..644..." +
                "..22575..." +
                "..44bb...." +
                "..8a.5a...",
                ".........." +
                ".........." +
                ".........." +
                "1........." +
                "1..1.3...." +
                ".22644...." +
                ".44575...." +
                "..8a.5a...",
                ".........." +
                ".........." +
                "1........." +
                "1........." +
                ".221.3...." +
                ".46644...." +
                "..4575...." +
                "..8a.5a...",
                ".........." +
                ".........." +
                "1........." +
                "1........." +
                ".221.3...." +
                ".46644...." +
                "..4575...." +
                "..8a.5a...",
                ".........." +
                ".........." +
                ".........." +
                "1........." +
                "1..1.3...." +
                ".22644...." +
                ".44575...." +
                "..8a.5a...",
                ".........." +
                ".........." +
                ".........." +
                "....1.3..." +
                "11..644..." +
                "..22575..." +
                "..44bb...." +
                "..8a.5a...",
            });

            Add(animations, PixelAvatarAnimation.Sit, 130, false, PixelAvatarAnimation.SitIdle, new[]
            {
                ".........." +
                ".........." +
                ".........." +
                ".....1.3.." +
                ".....644.." +
                ".11.2575.." +
                "...24bb..." +
                "...8a5a...",
                ".........." +
                ".........." +
                "....1.3..." +
                "....644..." +
                "....575..." +
                "...2bb...." +
                ".1.266...." +
                "..18a55...",
            });

            Add(animations, PixelAvatarAnimation.SitIdle, 300, true, PixelAvatarAnimation.SitIdle, new[]
            {
                ".........." +
                ".........." +
                "....1.3..." +
                "....644..." +
                "....575..." +
                "...2bb...." +
                ".1.266...." +
                "..18a55...",
                ".........." +
                ".........." +
                "....1.3..." +
                "....644..." +
                "....575..." +
                "...2bb...." +
                ".1.266...." +
                "..18a55...",
                ".........." +
                ".........." +
                "....1.3..." +
                "....644..." +
                "....575..." +
                "...2bb...." +
                ".1.266...." +
                "..18a55...",
                ".........." +
                ".........." +
                "....1.3..." +
                "....644..." +
                "....575..." +
                "...2bb...." +
                ".1.266...." +
                "..18a55...",
                ".........." +
                ".........." +
                "....1.3..." +
                "....644..." +
                "....575..." +
                "...2bb...." +
                ".11266...." +
                "...8a55...",
                ".........." +
                ".........." +
                "....1.3..." +
                "....644..." +
                "....575..." +
                ".1.2bb...." +
                "..1266...." +
                "...8a55...",
            });

            Add(animations, PixelAvatarAnimation.Crouch, 130, false, PixelAvatarAnimation.CrouchIdle, new[]
            {
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                ".11..1.3.." +
                "...22644.." +
                "...44575.." +
                "...8a5a...",
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                ".....1.3.." +
                ".11..644.." +
                "...22575.." +
                "...8a5a...",
            });

            Add(animations, PixelAvatarAnimation.CrouchIdle, 300, true, PixelAvatarAnimation.CrouchIdle, new[]
            {
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                ".....1.3.." +
                ".11..644.." +
                "...22575.." +
                "...8a5a...",
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                ".....1.3.." +
                ".11..644.." +
                "...22575.." +
                "...8a5a...",
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                ".....1.3.." +
                ".11..644.." +
                "...22575.." +
                "...8a5a...",
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                ".....1.3.." +
                ".11..644.." +
                "...22575.." +
                "...8a5a...",
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                ".....1.3.." +
                ".1...644.." +
                "..122575.." +
                "...8a5a...",
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                ".....1.3.." +
                ".....644.." +
                ".1122575.." +
                "...8a5a...",
            });

            Add(animations, PixelAvatarAnimation.Sleep, 200, false, PixelAvatarAnimation.SleepIdle, new[]
            {
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                ".1...1.3.." +
                "..122644.." +
                "...44575.." +
                "...8a5a...",
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                ".1...1.3.." +
                "..122644.." +
                "...8a575..",
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                ".....1.3.." +
                "...22644.." +
                ".118a575..",
            });

            Add(animations, PixelAvatarAnimation.SleepIdle, 450, true, PixelAvatarAnimation.SleepIdle, new[]
            {
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                ".........." +
                ".....1.3.." +
                "...22644.." +
                ".118a575..",
            });

            return animations;
        }

        private static void Add(
            Dictionary<PixelAvatarAnimation, PixelSpriteAnimation> animations,
            PixelAvatarAnimation                                  animation,
            int                                                   frameDurationMs,
            bool                                                  loops,
            PixelAvatarAnimation                                  next,
            string[]                                              packedFrames)
        {
            var frames = new PixelSprite[packedFrames.Length];
            for (var i = 0; i < packedFrames.Length; i++)
            {
                frames[i] = Decode(packedFrames[i]);
            }

            animations[animation] = new PixelSpriteAnimation(animation, frames, frameDurationMs, loops, next);
        }

        private static PixelSprite Decode(string packed)
        {
            var pixels = new byte[FrameWidth * FrameHeight];
            for (var i = 0; i < pixels.Length; i++)
            {
                var index = Alphabet.IndexOf(packed[i]);
                pixels[i] = (byte)(index < 0 ? 0 : index);
            }

            return new PixelSprite(FrameWidth, FrameHeight, pixels);
        }
    }
}
