// <auto-generated />
// Designs and palettes for the PixelAvatar component. Each entry maps palette index 1..N
// to a CSS color; index 0 is transparent and is not stored. The first designs are
// extracted from the source cat sprite sheets; the rest are authored against the same
// index roles. The enum lives here so a new design is a single edit. Do not edit by hand.

using System.Collections.Generic;
using Transpose;

namespace Tesserae
{
    /// <summary>
    /// The available coat designs for a <see cref="PixelAvatar"/>. All designs share the same
    /// artwork and differ only in their <see cref="PixelAvatarPalette"/>.
    /// </summary>
    [Enum(Emit.StringName)]
    [Transpose.Name("tss.PixelAvatarDesign")]
    public enum PixelAvatarDesign
    {
        [Name("Black")]         Black,
        [Name("Orange")]        Orange,
        [Name("White")]         White,
        [Name("Beige")]         Beige,
        [Name("Siamese")]       Siamese,
        [Name("SpottedGrey")]   SpottedGrey,
        [Name("SpottedOrange")] SpottedOrange,
        [Name("Tuxedo")]        Tuxedo,
        [Name("Grey")]          Grey,
        [Name("Sparkle")]       Sparkle,
        [Name("Lynx")]          Lynx
    }

    /// <summary>
    /// The built-in <see cref="PixelAvatarPalette"/> for each <see cref="PixelAvatarDesign"/>.
    /// </summary>
    [Transpose.Name("tss.PixelAvatarPalettes")]
    public static class PixelAvatarPalettes
    {
        private static readonly Dictionary<PixelAvatarDesign, PixelAvatarPalette> _palettes = Build();

        /// <summary>
        /// Returns the palette for one of the built-in designs.
        /// </summary>
        public static PixelAvatarPalette Get(PixelAvatarDesign design) => _palettes[design];

        /// <summary>
        /// Returns every built-in design, in declaration order.
        /// </summary>
        public static PixelAvatarDesign[] All => new[]
        {
            PixelAvatarDesign.Black,
            PixelAvatarDesign.Orange,
            PixelAvatarDesign.White,
            PixelAvatarDesign.Beige,
            PixelAvatarDesign.Siamese,
            PixelAvatarDesign.SpottedGrey,
            PixelAvatarDesign.SpottedOrange,
            PixelAvatarDesign.Tuxedo,
            PixelAvatarDesign.Grey,
            PixelAvatarDesign.Sparkle,
            PixelAvatarDesign.Lynx,
        };

        private static Dictionary<PixelAvatarDesign, PixelAvatarPalette> Build()
        {
            var palettes = new Dictionary<PixelAvatarDesign, PixelAvatarPalette>();

            palettes[PixelAvatarDesign.Black] = new PixelAvatarPalette("Black", new[] { "#625565", "#625565", "#625565", "#3E3546", "#3E3546", "#3E3546", "#3E3546", "#3E3546", "#3E3546", "#2E222F", "#2E222F" });
            palettes[PixelAvatarDesign.Orange] = new PixelAvatarPalette("Orange", new[] { "#F79617", "#F79617", "#F79617", "#FB6B1D", "#FB6B1D", "#FB6B1D", "#FB6B1D", "#FB6B1D", "#FB6B1D", "#E83B3B", "#E83B3B" });
            palettes[PixelAvatarDesign.White] = new PixelAvatarPalette("White", new[] { "#FFFFFF", "#FFFFFF", "#FFFFFF", "#C7DCD0", "#C7DCD0", "#C7DCD0", "#C7DCD0", "#C7DCD0", "#C7DCD0", "#9BABB2", "#9BABB2" });
            palettes[PixelAvatarDesign.Beige] = new PixelAvatarPalette("Beige", new[] { "#FDCBB0", "#FDCBB0", "#FDCBB0", "#FCA790", "#FCA790", "#FCA790", "#FCA790", "#FCA790", "#FCA790", "#F68181", "#F68181" });
            palettes[PixelAvatarDesign.Siamese] = new PixelAvatarPalette("Siamese", new[] { "#3E3546", "#FDE3D5", "#3E3546", "#FDCBB0", "#625565", "#FDCBB0", "#3E3546", "#625565", "#FDCBB0", "#3E3546", "#FCA790" });
            palettes[PixelAvatarDesign.SpottedGrey] = new PixelAvatarPalette("SpottedGrey", new[] { "#FFFFFF", "#FFFFFF", "#9BABB2", "#9BABB2", "#C7DCD0", "#C7DCD0", "#C7DCD0", "#9BABB2", "#C7DCD0", "#7E8F96", "#7E8F96" });
            palettes[PixelAvatarDesign.SpottedOrange] = new PixelAvatarPalette("SpottedOrange", new[] { "#FFFFFF", "#FFFFFF", "#F9C22B", "#F79617", "#C7DCD0", "#C7DCD0", "#C7DCD0", "#F79617", "#C7DCD0", "#9BABB2", "#9BABB2" });
            palettes[PixelAvatarDesign.Tuxedo] = new PixelAvatarPalette("Tuxedo", new[] { "#625565", "#625565", "#625565", "#3E3546", "#3E3546", "#3E3546", "#3E3546", "#3E3546", "#C7DCD0", "#2E222F", "#9BABB2" });

            // Authored rather than extracted:
            palettes[PixelAvatarDesign.Grey] = new PixelAvatarPalette("Grey", new[] { "#C9CDD4", "#C9CDD4", "#C9CDD4", "#98A0AC", "#98A0AC", "#98A0AC", "#98A0AC", "#98A0AC", "#98A0AC", "#646C7A", "#646C7A" });  // A plain neutral grey, built from three shades like the other single-hue coats.
            palettes[PixelAvatarDesign.Sparkle] = new PixelAvatarPalette("Sparkle", new[] { "#E7D6FF", "#F7EEFF", "#F19BEC", "#C63FE3", "#9366F5", "#9366F5", "#9366F5", "#C63FE3", "#F0E5FF", "#4C1D95", "#B9A2F2" });  // A violet coat with luminous magenta markings and a pale chest.
            palettes[PixelAvatarDesign.Lynx] = new PixelAvatarPalette("Lynx", new[] { "#E3CDA8", "#F0E2C8", "#9A7448", "#7A5630", "#C4A375", "#C4A375", "#C4A375", "#7A5630", "#F5EAD6", "#5A3F24", "#C7B291" });  // A tawny coat with dark brown ear tufts and spots over a cream chest.

            return palettes;
        }
    }
}
